name: Despliegue de backend en AWS

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
  
  steps:
      - name: 1.- Checkout a la version del code
        uses: actions/checkout@v3

